--CREATE DATABASE CigarShop4;
--USE CigarShop4;

CREATE TABLE Sizes
(
		Id INT PRIMARY KEY IDENTITY,
		Length INT NOT NULL CHECK (Length BETWEEN 10 AND 25),
		RingRange DECIMAL(15,2) NOT NULL CHECK (RingRange BETWEEN 1.5 AND 7.5)
);
CREATE TABLE Tastes
(
	Id INT PRIMARY KEY IDENTITY,
	TasteType VARCHAR(20) NOT NULL,
	TasteStrength VARCHAR(15) NOT NULL,
	ImageURL NVARCHAR(100) NOT NULL
);
CREATE TABLE Brands
(
	Id INT PRIMARY KEY IDENTITY,
	BrandName VARCHAR(30) UNIQUE NOT NULL,
	BrandDescription VARCHAR(MAX)
)
CREATE TABLE Cigars
(
	Id INT PRIMARY KEY IDENTITY,
	CigarName VARCHAR(80) NOT NULL,
	BrandId INT NOT NULL,
	TastId INT NOT NULL,
	SizeId INT NOT NULL,
	PriceForSingleCigar DECIMAL(15,2) NOT NULL,
	ImageURL NVARCHAR(100) NOT NULL
	CONSTRAINT fk_cigars_brands
		FOREIGN KEY (BrandId)
		REFERENCES Brands(Id),
	CONSTRAINT fk_cigars_tastes
		FOREIGN KEY (TastId)
		REFERENCES Tastes(Id),
	CONSTRAINT fk_cigars_sizes
		FOREIGN KEY (SizeId)
		REFERENCES Sizes(Id)
)
CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY,
	Town VARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	Streat NVARCHAR(100) NOT NULL,
	ZIP VARCHAR(20) NOT NULL
)
CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName  NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	AddressId INT NOT NULL
	CONSTRAINT fk_client_addresses
		FOREIGN KEY(AddressId)
		REFERENCES Addresses(Id)
)
CREATE TABLE ClientsCigars
(
	ClientId INT NOT NULL,
	CigarId INT NOT NULL
	CONSTRAINT pk_clients
		PRIMARY KEY(ClientId,CigarId)
	CONSTRAINT fk_cigars_clients
		FOREIGN KEY(ClientId)
		REFERENCES Clients(Id),
	CONSTRAINT fk_cigars_cigar
		FOREIGN KEY(CigarId)
		REFERENCES Cigars(Id)
)
